name: ecom_express
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  table_calendar: ^3.1.2
  http: ^1.2.2
  shared_preferences: ^2.0.0
  jwt_decoder:
  flutter_secure_storage: ^7.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/overtime.jpg
    - assets/advance.jpg
    - assets/remark.jpg
    - assets/business.png
    - assets/inactive.png
    - assets/icon.jpg
